#!/bin/bash

set -e 

echo
echo "### HOOK - build environment:"
echo "   SOURCE_BRANCH  : $SOURCE_BRANCH"
echo "   SOURCE_COMMIT  : $SOURCE_COMMIT"
echo "   COMMIT_MSG     : $COMMIT_MSG"
echo "   DOCKER_REPO    : $DOCKER_REPO"
echo "   DOCKERFILE_PATH: $DOCKERFILE_PATH"
echo "   DOCKER_TAG     : $DOCKER_TAG"
echo "   DOCKER_TAG     : $IMAGE_NAME"

echo
docker buildx build  --platform linux/amd64 -f ./amd64.dockerfile -t ${DOCKER_REPO}:amd64-${DOCKER_TAG} .
docker buildx build  --platform linux/amd64 -f ./amd64.dockerfile -t ${DOCKER_REPO}:amd64-latest .
docker buildx build  --platform linux/amd64 -f ./amd64.student.dockerfile -t ${DOCKER_REPO}:amd64-student-${DOCKER_TAG} .

docker buildx build --platform linux/arm64 -f ./arm64.dockerfile -t ${DOCKER_REPO}:arm64-${DOCKER_TAG} .
docker buildx build --platform linux/arm64 -f ./arm64.dockerfile -t ${DOCKER_REPO}:arm64-latest .
docker buildx build --platform linux/arm64 -f ./arm64.student.dockerfile  -t ${DOCKER_REPO}:arm64-student-${DOCKER_TAG} .